name: Windows-Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download & install essentials
        shell: cmd
        run: |
          echo Downloading Downloads.bat...
          powershell -Command "Invoke-WebRequest -Uri 'https://gitlab.com/chamod12/1m_win-10_github_rdp/-/raw/main/Downloads.bat' -OutFile 'Downloads.bat'"
          echo Running Downloads.bat...
          call Downloads.bat

      - name: Connect to LiteManager
        shell: cmd
        run: |
          echo Running show.bat...
          if exist show.bat (
            call show.bat
          ) else (
            echo ERROR: show.bat not found!
            exit /b 1
          )

      - name: Time Counter
        shell: cmd
        run: |
          echo Running loop.bat...
          if exist loop.bat (
            call loop.bat
          ) else (
            echo ERROR: loop.bat not found!
            exit /b 1
          )
