name: Ubuntu Runner

on:
  workflow_dispatch:

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show OS info
        run: |
          uname -a
          lsb_release -a || cat /etc/os-release

      - name: Update & install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl git zip unzip

      - name: Run your commands
        run: |
          echo "Hello from Ubuntu!"
          # Add your bash commands here
